### ISSUE TITLE
Links aren't usable in Live preview mode

### ISSUE THREAD

**Issue by joshuar** [matthewhchan/linkify#4]
Hey there,

Nice plugin! Thanks for making it!

It looks like when using Live preview mode, while you can create links, you can't use them (i.e., click on them on a desktop to be taken to the link's destination). Switching to reading mode allows the links to work as expected.

I'm using Obsidian 0.14.5 and Linkify 1.0.10 (downloaded from the releases page and installed using [Plugins Galore](https://github.com/plugins-galore/obsidian-plugins-galore))

Let me know if there is more information I can provide that would help!

**Comment by matthewhchan** [comment]
Thanks for trying out my plugin!

Links in Live Preview mode work for me on MacOS. My version of Obsidian is 0.15.2 (installer version v0.14.6).

Some things you might want to check:
- Temporarily disable other Community Plugins and restart Obsidian to see if there's a conflict.
- Change your theme to the Default theme, in case there's a conflict.
- Double check that your link starts with "http://" or "https://".

I'm currently trying to add this plugin to the official Community Plugins list, which should help eliminate installation errors (if that's the issue), but it looks like no new plugins have been approved for a couple of weeks.

**Comment by joshuar** [comment]
Hey thanks for getting back to me! So yeah, I see the plugin is now available in the official Community Plugins list, and I've installed the newer version from there. Lo and behold, links work in live preview mode :tada: 

So all working now, not sure what happened before. I'll keep in mind those tips about what to try if it happens again. But otherwise, probably can close this issue and can always re-open if it reoccurs?

Thanks again for the great plugin!

**Comment by matthewhchan** [comment]
Great! Glad it works for you now.
