### ISSUE TITLE
main.js missing from 1.0.11

### ISSUE THREAD

**Issue by PJnes** [matthewhchan/linkify#6]
This plugin looks interesting, but the latest version doesn't include a main.js file, so Obisidan can't enable it.

```
Plugin failure: linkify Error: ENOENT: no such file or directory, open '...\.obsidian\plugins\linkify\main.js'
```

Plugin directory just contains `manifest.json` and `styles.css`

**Comment by matthewhchan** [comment]
Thanks for telling me about this. I had accidentally added `main.ts` to the release instead of `main.js`. It should be fixed now.
